version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: projeto_incluir_user
      MYSQL_PASSWORD: projeto_incluir_pw
      MYSQL_DATABASE: projeto_incluir_db

  api:
    build: ../API
    ports:
      - '8002:8002'
    environment:
      PORT: 8002
    volumes:
      - ../API:/usr/src/app
    links:
      - db
    depends_on:
      - db

  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
      - cadastro-front-end
      - admin-app
      - php-my-admin
    depends_on:
      - api

  cadastro-front-end:
    build: ../CadastroFrontEnd
    ports:
      - '8003:8003'
    environment:
      PORT: 8003
    volumes:
      - ../CadastroFrontEnd:/usr/src/app
    links:
      - api
    depends_on:
      - api

  admin-app:
    build: ../AdminApp
    ports:
      - '8001:80'
    volumes:
      - ../AdminApp:/var/www/html
    links:
      - db
    depends_on:
      - db

  php-my-admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8004:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: projeto_incluir_user
      PMA_PASSWORD: projeto_incluir_pw
    links:
      - db
    depends_on:
      - db
