version: '2'
services:
  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  admin-app:
    build: ../AdminApp
    ports:
      - '1337:80'
    volumes:
      - ../AdminApp:/var/www/html
    depends_on:
      - database
volumes:
  db:
