admin-app:
  environment:
    - APPLICATION_ENV=production
    - DB_HOST=
    - DB_NAME=
    - DB_PASSWORD=
    - DB_USERNAME=
  expose:
    - '80'
  image: 'projetoincluiraws/admin-app:latest'
  restart: always
api:
  environment:
    - JWT_SEGREDO=
    - MYSQL_BANCO=
    - MYSQL_HOST=
    - MYSQL_PORTA=3306
    - MYSQL_SENHA=
    - MYSQL_USUARIO=
    - RESETAR_SENHA_EMAIL_REMETENTE=
    - RESETAR_SENHA_SENHA_REMETENTE=
    - RE_CAPTCHA_SECRET=
    - 'RE_CAPTCHA_URL=https://www.google.com/recaptcha/api/siteverify'
  expose:
    - '8002'
  image: 'projetoincluiraws/api:latest'
  restart: always
php-my-admin:
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=
    - PMA_PORT=3306
  expose:
    - '80'
  image: 'phpmyadmin/phpmyadmin:latest'
  restart: always
proxy-reverso:
  image: 'projetoincluiraws/proxyreverso:latest'
  links:
    - admin-app
    - api
    - php-my-admin
  ports:
    - '80:80'
    - '443:443'
  restart: always
