version: '3'
services:

  cadastro-app-front-end:
    build: ../CadastroAppFrontEnd
    ports:
      - '8003:8080'
    volumes:
      - ../CadastroAppFrontEnd:/usr/src/app
    links:
      - cadastro-app-api
    depends_on:
      - cadastro-app-api

  cadastro-app-api:
    build: ../CadastroAppAPI
    ports:
      - '8002:8080'
    links:
      - db
    volumes:
      - ../CadastroAppAPI:/usr/src/app
    depends_on:
      - db

  admin-app:
    build: ../AdminApp
    ports:
      - '8001:80'
    links:
      - db
    volumes:
      - ../AdminApp:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: projeto_incluir_user
      MYSQL_PASSWORD: projeto_incluir_pw
      MYSQL_DATABASE: projeto_incluir_db
